# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b8e6b2ac2764bca4a2f8a4b1ba14fdf"
name = "kc-cash-register-sync"
application_url = "https://northweblabs.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://northweblabs.com/api/shopify/oauth/callback" ]
