export type Puzzle = { id: number; cat: string; q: string; a: string };

export const PUZZLES: Puzzle[] = [
  { id: 1, cat: "Riddle", q: "What has keys but can't open locks?", a: "A piano." },
  { id: 2, cat: "Riddle", q: "What has hands but cannot clap?", a: "A clock." },
  { id: 3, cat: "Riddle", q: "What gets wetter the more it dries?", a: "A towel." },
  { id: 4, cat: "Riddle", q: "What has a neck but no head?", a: "A bottle." },
  { id: 5, cat: "Riddle", q: "What has many teeth but cannot bite?", a: "A comb." },
  { id: 6, cat: "Riddle", q: "What has an eye but cannot see?", a: "A needle." },
  { id: 7, cat: "Riddle", q: "What can travel around the world while staying in a corner?", a: "A stamp." },
  { id: 8, cat: "Riddle", q: "What has a thumb and four fingers but is not alive?", a: "A glove." },
  { id: 9, cat: "Riddle", q: "What has cities but no houses, forests but no trees, and water but no fish?", a: "A map." },
  { id: 10, cat: "Riddle", q: "What goes up but never comes down?", a: "Your age." },
  { id: 11, cat: "Riddle", q: "What has words but never speaks?", a: "A book." },
  { id: 12, cat: "Riddle", q: "What has a head and a tail but no body?", a: "A coin." },
  { id: 13, cat: "Riddle", q: "The more you take, the more you leave behind. What are they?", a: "Footsteps." },
  { id: 14, cat: "Riddle", q: "What can you catch but not throw?", a: "A cold." },
  { id: 15, cat: "Riddle", q: "What building has the most stories?", a: "A library." },
  { id: 16, cat: "Riddle", q: "What kind of band never plays music?", a: "A rubber band." },
  { id: 17, cat: "Riddle", q: "What has a ring but no finger?", a: "A telephone." },
  { id: 18, cat: "Riddle", q: "What runs but never walks, has a bed but never sleeps?", a: "A river." },
  { id: 19, cat: "Riddle", q: "What can fill a room but takes up no space?", a: "Light." },
  { id: 20, cat: "Riddle", q: "What has legs but doesn't walk?", a: "A table." },
  { id: 21, cat: "Riddle", q: "What is full of holes but still holds water?", a: "A sponge." },
  { id: 22, cat: "Riddle", q: "What gets bigger the more you take away?", a: "A hole." },
  { id: 23, cat: "Riddle", q: "What word is spelled wrong in every dictionary?", a: "Wrong." },
  { id: 24, cat: "Riddle", q: "What begins with T, ends with T, and has T in it?", a: "A teapot." },
  { id: 25, cat: "Riddle", q: "I have branches but no fruit, trunk, or leaves. What am I?", a: "A bank." },
  { id: 26, cat: "Riddle", q: "What can you keep after giving it to someone?", a: "Your word." },
  { id: 27, cat: "Riddle", q: "I'm tall when young and short when old. What am I?", a: "A candle." },
  { id: 28, cat: "Riddle", q: "What goes through cities and fields but never moves?", a: "A road." },
  { id: 29, cat: "Riddle", q: "What has a spine but no bones?", a: "A book." },
  { id: 30, cat: "Riddle", q: "What invention lets you look right through a wall?", a: "A window." },

  { id: 31, cat: "Lateral", q: "Two fathers and two sons go fishing and catch three fish, one each. How?", a: "They are grandfather, father, and son — only three people." },
  { id: 32, cat: "Lateral", q: "A doctor gives you 3 pills, one every half hour. How long until all are taken?", a: "One hour." },
  { id: 33, cat: "Lateral", q: "You see a boat full of people but not a single person on board. How?", a: "Everyone aboard is married." },
  { id: 34, cat: "Lateral", q: "A rooster lays an egg on a peaked roof. Which side does it roll down?", a: "Roosters don't lay eggs." },
  { id: 35, cat: "Lateral", q: "How many months have 28 days?", a: "All 12 of them." },
  { id: 36, cat: "Lateral", q: "If a plane crashes on the border of two countries, where do you bury the survivors?", a: "You don't bury survivors." },
  { id: 37, cat: "Lateral", q: "A farmer has 17 sheep; all but 9 die. How many are left?", a: "Nine." },
  { id: 38, cat: "Lateral", q: "Before Mount Everest was discovered, what was the tallest mountain on Earth?", a: "Mount Everest — it was still tallest, just undiscovered." },
  { id: 39, cat: "Lateral", q: "You're in a race and pass the person in 2nd place. What place are you in now?", a: "Second place." },
  { id: 40, cat: "Lateral", q: "A man pushes his car to a hotel and loses his fortune. What happened?", a: "He's playing Monopoly." },
  { id: 41, cat: "Lateral", q: "What can you hold in your left hand but never in your right?", a: "Your right elbow." },
  { id: 42, cat: "Lateral", q: "The maker sells it, the buyer never uses it, the user never sees it. What is it?", a: "A coffin." },
  { id: 43, cat: "Lateral", q: "Which weighs more: a pound of feathers or a pound of bricks?", a: "They weigh the same — one pound." },
  { id: 44, cat: "Lateral", q: "How many times can you subtract 5 from 25?", a: "Once — after that it's 20, not 25." },
  { id: 45, cat: "Lateral", q: "If two's company and three's a crowd, what are four and five?", a: "Nine." },

  { id: 46, cat: "Math", q: "I'm an odd number. Take away one letter and I become even. What number am I?", a: "Seven (remove the 's' to get 'even')." },
  { id: 47, cat: "Math", q: "Using only addition, add eight 8s to make 1000.", a: "888 + 88 + 8 + 8 + 8 = 1000." },
  { id: 48, cat: "Math", q: "A bat and ball cost $1.10. The bat costs $1 more than the ball. How much is the ball?", a: "5 cents." },
  { id: 49, cat: "Math", q: "A snail climbs 3 ft up by day and slips 2 ft at night in a 10 ft well. How many days to escape?", a: "8 days." },
  { id: 50, cat: "Math", q: "If 5 machines take 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", a: "5 minutes." },
  { id: 51, cat: "Math", q: "Lily pads double daily and fill a lake in 48 days. On what day is the lake half full?", a: "Day 47." },
  { id: 52, cat: "Math", q: "What is the sum of all whole numbers from 1 to 100?", a: "5050." },
  { id: 53, cat: "Math", q: "A clock takes 5 seconds to strike 6. How long to strike 12?", a: "11 seconds (the gaps, not the strikes)." },
  { id: 54, cat: "Math", q: "If you multiply together every number on a phone keypad, what's the product?", a: "Zero." },
  { id: 55, cat: "Math", q: "What three positive whole numbers give the same answer when multiplied as when added?", a: "1, 2, and 3." },
  { id: 56, cat: "Math", q: "What is half of two, plus two?", a: "Three." },
  { id: 57, cat: "Math", q: "A number's double is 12 more than its half. What is the number?", a: "Eight." },
  { id: 58, cat: "Math", q: "With socks of two colours in a dark drawer, how many must you draw to guarantee a matching pair?", a: "Three." },
  { id: 59, cat: "Math", q: "What is the angle between the hands of a clock at 3:15?", a: "7.5 degrees." },
  { id: 60, cat: "Math", q: "A girl has as many brothers as sisters, but each brother has half as many brothers as sisters. How many of each?", a: "4 sisters and 3 brothers." },

  { id: 61, cat: "Sequence", q: "What comes next: 1, 1, 2, 3, 5, 8, ?", a: "13 (Fibonacci)." },
  { id: 62, cat: "Sequence", q: "What comes next: 2, 4, 8, 16, ?", a: "32 (doubling)." },
  { id: 63, cat: "Sequence", q: "What comes next: 1, 4, 9, 16, 25, ?", a: "36 (square numbers)." },
  { id: 64, cat: "Sequence", q: "What comes next: O, T, T, F, F, S, S, ?", a: "E (initials of one, two, three… eight)." },
  { id: 65, cat: "Sequence", q: "What comes next: 1, 11, 21, 1211, 111221, ?", a: "312211 (look-and-say)." },
  { id: 66, cat: "Sequence", q: "What comes next: 3, 6, 11, 18, 27, ?", a: "38 (gaps grow by 2)." },
  { id: 67, cat: "Sequence", q: "What comes next: J, F, M, A, M, J, ?", a: "J (first letters of the months)." },
  { id: 68, cat: "Sequence", q: "What comes next: 1, 2, 6, 24, 120, ?", a: "720 (factorials)." },
  { id: 69, cat: "Sequence", q: "What comes next: 2, 3, 5, 7, 11, ?", a: "13 (prime numbers)." },
  { id: 70, cat: "Sequence", q: "What comes next: 1, 8, 27, 64, ?", a: "125 (cubes)." },

  { id: 71, cat: "Word", q: "What word contains all the letters needed to spell the alphabet's name?", a: "Alphabet." },
  { id: 72, cat: "Word", q: "What English word has three consecutive double letters?", a: "Bookkeeper." },
  { id: 73, cat: "Word", q: "What occurs once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M." },
  { id: 74, cat: "Word", q: "What 4-letter word reads the same forwards, backwards, and upside down?", a: "NOON." },
  { id: 75, cat: "Word", q: "What 5-letter word becomes shorter when you add two letters?", a: "Short." },
  { id: 76, cat: "Word", q: "What starts with E, ends with E, but contains only one letter?", a: "An envelope." },
  { id: 77, cat: "Word", q: "What word is always spelled incorrectly?", a: "Incorrectly." },
  { id: 78, cat: "Word", q: "Forward I am heavy, but backward I am not. What word am I?", a: "Ton." },
  { id: 79, cat: "Word", q: "What 5-letter word is pronounced the same even after removing four of its letters?", a: "Queue." },
  { id: 80, cat: "Word", q: "I am an English word made of M and T, said aloud, that means 'nothing inside'. What am I?", a: "Empty." },

  { id: 81, cat: "Trivia", q: "What planet is known as the Red Planet?", a: "Mars." },
  { id: 82, cat: "Trivia", q: "What is the largest mammal on Earth?", a: "The blue whale." },
  { id: 83, cat: "Trivia", q: "What gas do plants absorb from the air?", a: "Carbon dioxide." },
  { id: 84, cat: "Trivia", q: "How many continents are there?", a: "Seven." },
  { id: 85, cat: "Trivia", q: "What is the chemical symbol for gold?", a: "Au." },
  { id: 86, cat: "Trivia", q: "What is the hardest known natural substance?", a: "Diamond." },
  { id: 87, cat: "Trivia", q: "How many bones are in the adult human body?", a: "206." },
  { id: 88, cat: "Trivia", q: "What is the smallest prime number?", a: "2." },
  { id: 89, cat: "Trivia", q: "What is the capital of Japan?", a: "Tokyo." },
  { id: 90, cat: "Trivia", q: "How many colours are in a rainbow?", a: "Seven." },
  { id: 91, cat: "Trivia", q: "What is the largest planet in our solar system?", a: "Jupiter." },
  { id: 92, cat: "Trivia", q: "What organ pumps blood through the body?", a: "The heart." },
  { id: 93, cat: "Trivia", q: "What is the freezing point of water in Celsius?", a: "0 degrees." },
  { id: 94, cat: "Trivia", q: "How many strings does a standard guitar have?", a: "Six." },
  { id: 95, cat: "Trivia", q: "What is the tallest land animal?", a: "The giraffe." },
  { id: 96, cat: "Trivia", q: "What metal is liquid at room temperature?", a: "Mercury." },
  { id: 97, cat: "Trivia", q: "What is often called the powerhouse of the cell?", a: "The mitochondria." },
  { id: 98, cat: "Trivia", q: "How many sides does a hexagon have?", a: "Six." },
  { id: 99, cat: "Trivia", q: "Which language has the most native speakers worldwide?", a: "Mandarin Chinese." },
  { id: 100, cat: "Trivia", q: "Approximately how fast does light travel, in km per second?", a: "About 300,000 km/s." },
];
